apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: svc-lb-kuard
  namespace:
spec:
  ports:
  - nodePort: 32333
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: LoadBalancer
