apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-limited
  name: svc-lb-nginx-limited
  namespace:
spec:
  ports:
  - nodePort: 32444
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-limited
  sessionAffinity: None
  type: LoadBalancer
