apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: svc-lb-nginx
  namespace:
spec:
  ports:
  - nodePort: 32222
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
